lib/marketplace_web/router.ex
defmodule MarketplaceWeb.Router do
  use MarketplaceWeb, :router

  import MarketplaceWeb.PlayerAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_player
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MarketplaceWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", MarketplaceWeb do
  #   pipe_through :api
  # end

  ## Authentication routes

  scope "/", MarketplaceWeb do
    pipe_through [:browser, :redirect_if_player_is_authenticated]

    get "/player/register", PlayerRegistrationController, :new
    post "/player/register", PlayerRegistrationController, :create
    get "/player/log_in", PlayerSessionController, :new
    post "/player/log_in", PlayerSessionController, :create
    get "/player/reset_password", PlayerResetPasswordController, :new
    post "/player/reset_password", PlayerResetPasswordController, :create
    get "/player/reset_password/:token", PlayerResetPasswordController, :edit
    put "/player/reset_password/:token", PlayerResetPasswordController, :update
  end

  scope "/", MarketplaceWeb do
    pipe_through [:browser, :require_authenticated_player]

    get "/player/settings", PlayerSettingsController, :edit
    put "/player/settings", PlayerSettingsController, :update
    get "/player/settings/confirm_email/:token", PlayerSettingsController, :confirm_email
    resources "/generators", GeneratorController
    resources "/resources", ResourceController
    resources "/products", ProductController
    resources "/plots", PlotController
    resources "/players", PlayerController
  end

  scope "/", MarketplaceWeb do
    pipe_through [:browser]

    delete "/player/log_out", PlayerSessionController, :delete
    get "/player/confirm", PlayerConfirmationController, :new
    post "/player/confirm", PlayerConfirmationController, :create
    get "/player/confirm/:token", PlayerConfirmationController, :confirm
  end
end

lib/marketplace_web/controllers/player_session_controller.ex
defmodule MarketplaceWeb.PlayerSessionController do
  use MarketplaceWeb, :controller

  alias Marketplace.Accounts
  alias MarketplaceWeb.PlayerAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"player" => player_params}) do
    %{"email" => email, "password" => password} = player_params

    if player = Accounts.get_player_by_email_and_password(email, password) do
      PlayerAuth.log_in_player(conn, player, player_params)
    else
      render(conn, "new.html", error_message: "Invalid email or password")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Logged out successfully.")
    |> PlayerAuth.log_out_player()
  end
end

lib/marketplace_web/views/player_session_view.ex
defmodule MarketplaceWeb.PlayerSessionView do
  use MarketplaceWeb, :view
end

lib/marketplace_web/templates/player_session/new.html.eex
<h1>Log in</h1>

<%= form_for @conn, Routes.player_session_path(@conn, :create), [as: :player], fn f -> %>
  <%= if @error_message do %>
    <div class="alert alert-danger">
      <p><%= @error_message %></p>
    </div>
  <% end %>

  <%= label f, :email %>
  <%= email_input f, :email, required: true %>

  <%= label f, :password %>
  <%= password_input f, :password, required: true %>

  <%= label f, :remember_me, "Keep me logged in for 60 days" %>
  <%= checkbox f, :remember_me %>

  <div>
    <%= submit "Log in" %>
  </div>
<% end %>

<p>
  <%= link "Register", to: Routes.player_registration_path(@conn, :new) %> |
  <%= link "Forgot your password?", to: Routes.player_reset_password_path(@conn, :new) %>
</p>