lib/marketplace_web/router.ex
defmodule MarketplaceWeb.Router do
  use MarketplaceWeb, :router

  import MarketplaceWeb.PlayerAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_player
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MarketplaceWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", MarketplaceWeb do
  #   pipe_through :api
  # end

  ## Authentication routes

  scope "/", MarketplaceWeb do
    pipe_through [:browser, :redirect_if_player_is_authenticated]

    get "/player/register", PlayerRegistrationController, :new
    post "/player/register", PlayerRegistrationController, :create
    get "/player/log_in", PlayerSessionController, :new
    post "/player/log_in", PlayerSessionController, :create
    get "/player/reset_password", PlayerResetPasswordController, :new
    post "/player/reset_password", PlayerResetPasswordController, :create
    get "/player/reset_password/:token", PlayerResetPasswordController, :edit
    put "/player/reset_password/:token", PlayerResetPasswordController, :update
  end

  scope "/", MarketplaceWeb do
    pipe_through [:browser, :require_authenticated_player]

    get "/player/settings", PlayerSettingsController, :edit
    put "/player/settings", PlayerSettingsController, :update
    get "/player/settings/confirm_email/:token", PlayerSettingsController, :confirm_email
    resources "/generators", GeneratorController
    resources "/resources", ResourceController
    resources "/products", ProductController
    resources "/plots", PlotController
    resources "/players", PlayerController
  end

  scope "/", MarketplaceWeb do
    pipe_through [:browser]

    delete "/player/log_out", PlayerSessionController, :delete
    get "/player/confirm", PlayerConfirmationController, :new
    post "/player/confirm", PlayerConfirmationController, :create
    get "/player/confirm/:token", PlayerConfirmationController, :confirm
  end
end

lib/marketplace_web/views/layout_view.ex
defmodule MarketplaceWeb.LayoutView do
  use MarketplaceWeb, :view
end

lib/marketplace_web/templates/layout/_player_menu.html.eex
<ul class="dropdown-menu" aria-labelledby="player-links">
  <li class="dropdown-item"><%= link "List", to: Routes.player_path(@conn, :index), class: "nav-link" %></li>
<%= if @current_player do %>
  <li class="dropdown-item"><%= @current_player.email %></li>
  <li class="dropdown-item"><%= link "Settings", to: Routes.player_settings_path(@conn, :edit), class: "nav-link" %></li>
  <li class="dropdown-item"><%= link "Log out", to: Routes.player_session_path(@conn, :delete), method: :delete, class: "nav-link" %></li>
<% else %>
  <li class="dropdown-item"><%= link "Register", to: Routes.player_registration_path(@conn, :new), class: "nav-link" %></li>
  <li class="dropdown-item"><%= link "Log in", to: Routes.player_session_path(@conn, :new), class: "nav-link" %></li>
<% end %>
</ul>

lib/marketplace_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Marketplace · Phoenix Framework</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  </head>
  <body>
    <header class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Marketplace</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item"><%= link "Resources", to: Routes.resource_path(@conn, :index), class: "nav-link" %></li>
              <li class="nav-item"><%= link "Generators", to: Routes.generator_path(@conn, :index), class: "nav-link" %></li>
              <li class="nav-item"><%= link "Plots", to: Routes.plot_path(@conn, :index), class: "nav-link" %></li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="player-links" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Players
                </a>
                <%= render "_player_menu.html", assigns %>
              </li>
            </ul>
          </div>
        </div>
        <%= render "_player_menu.html", assigns %>
      </nav>
    </header>
    <main role="main" class="container">
      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>
      <%= @inner_content %>
    </main>
  </body>
</html>